### ISSUE TITLE
TGDP needs a template for a README 

### ISSUE THREAD

**Issue by cwcromwell** [thegooddocsproject/templates#152] opened 2020-08-09 19:06 UTC
Projects on GitLab and GitHub need a readme with information such as: 

-- how to contribute to a project
-- project architecture
-- how to build the project locally (including depencies that you might have to install)
-- link to more documentation if it exists. 

There might be more needed in this outline.

**Comment by mjang** [comment] 2020-08-09 19:15
GitLab template example for GraphQL: https://docs.gitlab.com/ee/development/documentation/styleguide.html#graphql-api

**Comment by ScriptAutomate** [comment] 2020-08-09 20:35
This would be excellent for _The Good Docs Project_ repositories to reference, too. TGD has a repository that is missing a README, and could make use of it!

- [The Good Docs Project website source code](https://github.com/thegooddocsproject/thegooddocsproject.github.io)

**Comment by Loquacity** [comment] 2020-08-10 06:25
Possible duplicate? https://github.com/thegooddocsproject/templates/issues/110

**Comment by mjang** [comment] 2020-08-10 15:49
You're welcome to assign me an issue, @ScriptAutomate

**Comment by ScriptAutomate** [comment] 2020-08-12 19:32
@Loquacity Agreed. I think this issue should be closed as a duplicate of #110

**Comment by camerons** [comment] 2020-08-13 20:48
Closing this issues as a duplicate of #110 as suggested.
@mjang it would be great if you would like to take the lead on helping resolve this. Refer to proposed steps for resolution in #110. (Note, it is likely going to involve a lot of research, community liaison and negotiation.)

**Closed by camerons** 2020-08-13 20:48 UTC
